### ISSUE TITLE
MSSQL Support Fully Qualified Table Names

### ISSUE THREAD

**Issue by chuck-flowers** [kysely-org/kysely#1203] opened 2024-10-31 17:41 UTC
In MSSQL it is possible to reference tables from multiple databases within a single connection. This is accomplished by using a 3-part identifier like the following: `MyDatabase.dbo.MyTable`.

It appears that kysely doesn't currently support this. Is there a technical reason that prevents this from being supported or has it not yet been requested?

I'm more than happy to try to implement it if you're open to having the feature included in the project. After looking at the code, my first idea is to add an optional `database` property to the `SchemableIdentifier` type and support properly stringifying it  in the MssqlCompiler if that property is present. If there's something I'm overlooking please let me know.

**Comment by koskimas** [comment] 2024-10-31 18:26
It. This has come up, but implementing support for this would complicate the types a lot. It'd make the types more complex and considerably slower to compile for everyone. Not just mssql users.

You are overlooking types. The SQL part of it is relatively straight forward to implement. The types definitely isn't.

**Comment by chuck-flowers** [comment] 2024-10-31 19:20
I totally understand.

Since this has come up before, are there any recommended work arounds? Unfortunately the way the DBs are organized for this application requires doing cross-db joins.

**Comment by igalklebanov** [comment] 2024-10-31 20:05
Hey 👋 

A possible workaround would be a plugin that maps to/from 3 dot notation to 2 dot notation, so when you're writing your queries, you don't write `dbo`, just `[dbname].[tablename]`, but `[dbname].dbo.[tablename]` gets compiled.

**Comment by chuck-flowers** [comment] 2024-10-31 21:27
Thank you for the suggestions. That sounds like a workable solution on my end.

**Comment by chuck-flowers** [comment] 2024-11-02 03:55
@igalklebanov I took a stab at creating the plugin as you described but I'm running into another issue now. After mapping from 2 to 3, it seems that kysely is double quoting the result to escape the extra dot. Is there a way to get kysely to not escape the table name with double quotes?

**Comment by igalklebanov** [comment] 2024-12-29 18:48
Duplicate of #875.

**Closed by igalklebanov** 2024-12-29 18:48 UTC
Labels: duplicate, enhancement, wontfix, typescript, mssql

**Comment by DeryGaleas** [comment] 2025-01-02 23:00
@chuck-flowers  can you provide an example on how you extend/overrode MssqlQueryCompiler?

**Comment by chuck-flowers** [comment] 2025-01-06 17:25
Sure, here's an example of what we are currently using:

```typescript
import type { AppConfigSection } from './config.js';
import type { MssqlDialectConfig, SchemableIdentifierNode } from 'kysely';
import type { DB } from '../models/db.js';
import { Kysely, MssqlDialect, MssqlQueryCompiler } from 'kysely';
import * as tarn from 'tarn';
import * as tedious from 'tedious';

export function createKysely(config: KyselyConfig) {
	return new Kysely<DB>({
		dialect: new CustomDialect({
			aliases: {
				MyDb: '"MyDb"."dbo"',
			},
			tarn: {
				...tarn,
				options: {
					min: 1,
					max: 5,
				},
			},
			tedious: {
				...tedious,
				connectionFactory: () => createConnection({
					host: config.DB_HOST,
					port: config.DB_PORT,
					user: config.DB_USER,
					pass: config.DB_PASS,
				}),
			},
		}),
	});
}

function createConnection(config: { host: string; port: number; user: string, pass: string; }): tedious.Connection {
	return new tedious.Connection({
		server: config.host,
		options: {
			port: config.port,
			trustServerCertificate: true,
		},
		authentication: {
			type: 'default',
			options: {
				userName: config.user,
				password: config.pass,
			},
		},
	});
}

type KyselyConfig = AppConfigSection<'DB'>;

class CustomDialect extends MssqlDialect {
	constructor(private readonly config: CustomDialectConfig) {
		super(config);
	}

	override createQueryCompiler() {
		return new CustomQueryCompiler(this.config.aliases);
	}
}

interface CustomDialectConfig extends MssqlDialectConfig {
	aliases: AliasConfig;
}

class CustomQueryCompiler extends MssqlQueryCompiler {
	constructor(private readonly aliases: AliasConfig) {
		super();
	}

	override visitSchemableIdentifier(node: SchemableIdentifierNode) {
		const schema = node.schema;
		if (schema) {
			const expanded = this.aliases[schema.name];
			if (expanded) {
				super.append(expanded);
			} else {
				super.visitIdentifier(schema);
			}

			this.append('.');
		}

		super.visitIdentifier(node.identifier);
	}
}

type AliasConfig = Record<string, string>;


```
