### ISSUE TITLE
Allow beginTransaction and rollbackTransaction calls. 

### ISSUE THREAD

**Issue by seivan** [kysely-org/kysely#956] opened 2024-04-22 09:12 UTC
This is useful for unit tests that use the DB reference as a dependency injection on models.
By calling beginTransaction on setups and rollbacks on teardown, we can simulate an isolated sandbox environment for the database. 

This would be similar to [ecto](https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.Sandbox.html) where the death(?) of the process indicate the rollback. Since we can't rely on the many test runners to manage that, the easiest would be if one could call the functions manually and making sure that `db` is in a transaction during each test.

**Comment by igalklebanov** [comment] 2024-04-22 23:37
Hey 👋

Duplicate of #257.

**Closed** 2024-04-22 23:38 UTC
Labels: duplicate, enhancement, api
