### ISSUE TITLE
Kysely + bun = ReferenceError: Cannot access uninitialized variable

### ISSUE THREAD

**Issue by osejrafael** [kysely-org/kysely#412] opened 2023-04-03 20:02 UTC
Setting up a new project with Kysely and the PlanetScaleDialect. I get the following error after a simple query or even with I `console.log(db)`

The error:
```bash
 /// <reference types="./query-creator.d.ts" />
2 | import { SelectQueryBuilder } from './query-builder/select-query-builder.js';
   ^
ReferenceError: Cannot access uninitialized variable.
```

This is my `db.ts` file:
```typescript
import { Kysely } from "kysely";
import { PlanetScaleDialect } from "kysely-planetscale";
import { DB } from "./types/Database";

const db = new Kysely<DB>({
  dialect: new PlanetScaleDialect({
    host: process.env.DB_URL,
    username: process.env.DB_USER,
    password: process.env.DB_PASS,
    fetch: fetch,
    useSharedConnection: false,
  }),
});

export default db;
```

this is where I want to execute the query:
```typescript
import { Hono } from "hono";
import db from "./db";

const app = new Hono();

app.get("/", (c) => c.json({ message: "hello" }));

app.get("/test-data", async (c) => {
  console.log(db);
  // const testData = await db
  //   .selectFrom("testtable")
  //   .select(["id", "name"])
  //   .where("testtable.active", "=", 1)
  //   .execute();

  return c.json({ message: "test" });
});

export default app;
```

It works perfectly fine with just the planetscale driver (no kysely)

**My system info:**
Laptop: M2 Pro
Server: [bun](https://github.com/oven-sh/bun) 0.5.8
Global node version: 16.19
Global npm: 9.6

**Comment by igalklebanov** [comment] 2023-04-03 20:13
Hey 👋 

We've not tested Kysely on Bun.

Seems to be related to this [issue](https://github.com/oven-sh/bun/issues/1961).

**Comment by osejrafael** [comment] 2023-04-03 20:44
Thanks for pointing out the issue

**Comment by Jarred-Sumner** [comment] 2023-04-04 00:55
This is an ESM <> CJS module load order bug in Bun (not a bug in Kysely)

**Comment by Jarred-Sumner** [comment] 2023-04-17 05:23
Pushed a fix for this in the canary build of Bun

This canary build has quite a lot of changes (new bundler) so there could be other things that crop up, but if you want to try it:

```bash
bun upgrade --canary
```

Before:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/709451/232387014-ab63d96c-d2e1-412b-84ec-4a9120daac7e.png">

After:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/709451/232387125-791a2b3d-867f-4af5-881e-556ec6d04d7a.png">

**Comment by osejrafael** [comment] 2023-04-18 22:44
> Pushed a fix for this in the canary build of Bun
> 
> This canary build has quite a lot of changes (new bundler) so there could be other things that crop up, but if you want to try it:
> 
> ```shell
> bun upgrade --canary
> ```
> 
> Before:
> 
> <img alt="image" width="678" src="https://user-images.githubusercontent.com/709451/232387014-ab63d96c-d2e1-412b-84ec-4a9120daac7e.png">
> 
> After:
> 
> <img alt="image" width="572" src="https://user-images.githubusercontent.com/709451/232387125-791a2b3d-867f-4af5-881e-556ec6d04d7a.png">

Awesome! Will try later tonight

**Comment by osejrafael** [comment] 2023-04-18 22:45
Awesome! Will try later tonight @Jarred-Sumner

**Comment by osejrafael** [comment] 2023-04-19 04:56
Worked on bun version `0.6`! 🙌

**Closed** 2023-04-19 05:03 UTC
Labels: help wanted, invalid, custom dialect

**Comment by osejrafael** [comment] 2023-04-19 05:58
To be clear version `0.6` has not been released as of today. To use this version you need to run
```bash
bun upgrade --canary
```
as @Jarred-Sumner mentioned above
