### ISSUE TITLE
Compilation errors after upgrading to TypeScript 5.1.6 or newer.

### ISSUE THREAD

**Issue by virtuallyunknown** [kysely-org/kysely#567] opened 2023-07-07 00:39 UTC
Originally I posted this on the Discord server. Since then we I also found out the issue is specific to TypeScript version `5.1.6`.

Basically the when you try to build with `tsc`, it will throw an error related to `OnConflictUpdateBuilder`. Here is a bare-minimum repository where the issue can be reproduced, just clone and run `tsc` or `npm run check`.

https://github.com/virtuallyunknown/kysely-tsc-error/

Downgrading to version `5.1.3` **fixes the problem**.

We have also tested the following versions:

- `typescript@beta` - `5.2.0-beta`
- `typescript@next` - `5.2.0-dev.20230706`

But unfortunately it throws the exact same error there too.

```
> kysely-tsc-error@1.0.0 check
> tsc

src/countries.ts:7:27 - error TS2322: Type 'OnConflictUpdateBuilder<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>' is not assignable to type 'OnConflictDoNothingBuilder<DB, "countries"> | OnConflictUpdateBuilder<DB, "countries">'.
  Type 'OnConflictUpdateBuilder<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>' is not assignable to type 'OnConflictUpdateBuilder<DB, "countries">'.
    Types of property 'where' are incompatible.
      Type '{ <RE extends ReferenceExpression<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<...>): OnConflictUpdateBuilder<...>; (factory: WhereExpressionFactory<...>): OnConflictUpdateBuilder<...>; (expression: Expression<...>):...' is not assignable to type '{ <RE extends ReferenceExpression<DB, "countries">>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<DB, "countries", RE>): OnConflictUpdateBuilder<...>; (factory: WhereExpressionFactory<...>): OnConflictUpdateBuilder<...>; (expression: Expression<...>): OnConflictUpdateBuilder<...>; }'.
        Types of parameters 'factory' and 'factory' are incompatible.
          Types of parameters 'eb' and 'eb' are incompatible.
            Type 'WhereExpressionBuilder<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>' is not assignable to type 'WhereExpressionBuilder<DB, "countries">'.
              Types of property 'where' are incompatible.
                Type '{ <RE extends ReferenceExpression<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<...>): WhereExpressionBuilder<...>; (grouper: WhereExpressionBuilder<...>): WhereExpressionBuilder<...>; (expression: Expression<...>): W...' is not assignable to type '{ <RE extends ReferenceExpression<DB, "countries">>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<DB, "countries", RE>): WhereExpressionBuilder<...>; (grouper: WhereExpressionBuilder<...>): WhereExpressionBuilder<...>; (expression: Expression<...>): WhereExpressionBuilder<...>; }'.
                  Types of parameters 'grouper' and 'grouper' are incompatible.
                    Type 'WhereExpressionBuilder<DB, "countries">' is not assignable to type 'WhereExpressionBuilder<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>'.
                      Types of property 'whereRef' are incompatible.
                        Type '(lhs: ReferenceExpression<DB, "countries">, op: ComparisonOperatorExpression, rhs: ReferenceExpression<DB, "countries">) => WhereExpressionBuilder<...>' is not assignable to type '(lhs: ReferenceExpression<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>, op: ComparisonOperatorExpression, rhs: ReferenceExpression<...>) => WhereExpressionBuilder<...>'.
                          Types of parameters 'lhs' and 'lhs' are incompatible.
                            Type 'ReferenceExpression<OnConflictDatabase<DB, "countries">, OnConflictTables<"countries">>' is not assignable to type 'ReferenceExpression<DB, "countries">'.
                              Type '"excluded.id"' is not assignable to type 'ReferenceExpression<DB, "countries">'.

  7         .onConflict(oc => oc
                              ~~
  8             .column('id')
    ~~~~~~~~~~~~~~~~~~~~~~~~~
...
 10                 id: eb.ref('excluded.id')
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 11             }))
    ~~~~~~~~~~~~~~~

  node_modules/kysely/dist/esm/query-builder/insert-query-builder.d.ts:371:26
    371     onConflict(callback: (builder: OnConflictBuilder<DB, TB>) => OnConflictDoNothingBuilder<DB, TB> | OnConflictUpdateBuilder<DB, TB>): InsertQueryBuilder<DB, TB, O>;
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from the return type of this signature.


Found 1 error in src/countries.ts:7
```

**Comment by AzSiAz** [comment] 2023-07-07 17:56
Not sure it's completely fixed, I don't have `onConflict` issue anymore but I still have some typing issue only on typescript 5.1.6 but it's working fine on 5.0.2

```
TS2322: Type 'SelectQueryBuilder<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b", Selectable<...>>' is not assignable to type 'SelectQueryBuilder<Database & { b: BottleTable; }, "b", Selectable<BottleTable>>'.
         Types of property 'where' are incompatible.
           Type '{ <RE extends ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<...>): SelectQueryBuilder<...>; (facto...' is not assignable to type '{ <RE extends ReferenceExpression<Database & { b: BottleTable; }, "b">>(lhs: RE, op: ComparisonOperatorExpression, rhs: OperandValueExpressionOrList<...>): SelectQueryBuilder<...>; (factory: WhereExpressionFactory<...>): SelectQueryBuilder<...>; (expression: Expression<...>): SelectQueryBuilder<...>; }'.
             Types of parameters 'factory' and 'factory' are incompatible.
               Types of parameters 'eb' and 'eb' are incompatible.
                 Type 'ExpressionBuilder<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">' is not assignable to type 'ExpressionBuilder<Database & { b: BottleTable; }, "b">'.
                   The types of 'fn.agg' are incompatible between these types.
                     Type '<O>(name: string, args?: readonly ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">[] | undefined) => AggregateFunctionBuilder<...>' is not assignable to type '<O>(name: string, args?: readonly ReferenceExpression<Database & { b: BottleTable; }, "b">[] | undefined) => AggregateFunctionBuilder<Database & { b: BottleTable; }, "b", O>'.
                       Types of parameters 'args' and 'args' are incompatible.
                         Type 'readonly ReferenceExpression<Database & { b: BottleTable; }, "b">[] | undefined' is not assignable to type 'readonly ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">[] | undefined'.
                           Type 'readonly ReferenceExpression<Database & { b: BottleTable; }, "b">[]' is not assignable to type 'readonly ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">[]'.
                             Type 'ReferenceExpression<Database & { b: BottleTable; }, "b">' is not assignable to type 'ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">'.
                               Type 'SelectQueryBuilderFactory<Database & { b: BottleTable; }, "b", { [x: string]: any; }>' is not assignable to type 'ReferenceExpression<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b">'.
                                 Type 'SelectQueryBuilderFactory<Database & { b: BottleTable; }, "b", { [x: string]: any; }>' is not assignable to type 'SelectQueryBuilderFactory<{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }, "barcode" | "b", { ...; }>'.
                                   Type '{ aromaticProfileGraph: AromaticProfileGraphTable; country: CountryTable; brand: BrandTable; bottle: BottleTable; ... 15 more ...; b: BottleTable; }' is not assignable to type 'Database & { b: BottleTable; }'.
```

**Comment by igalklebanov** [comment] 2023-07-07 18:02
@AzSiAz Damn, can you provide a small reproduction repository?

**Comment by AzSiAz** [comment] 2023-07-07 18:11
It's 8PM on my timezone so I will be back to you tomorrow with a reproduction repository as soon as possible 😄

**Comment by koskimas** [comment] 2023-07-07 18:17
https://kyse.link repro is fine too

**Comment by koskimas** [comment] 2023-07-08 09:56
@AzSiAz if you don't have time to write a reproduction, could you paste the failing query here? We could be able to guess the problem from that.

**Comment by AzSiAz** [comment] 2023-07-08 11:14
Sorry, I will have some time to make a reproduction in 2 or 3 hours 🤞 

Here is the query part

```ts
let baseQuery = kysely.withPlugin(new DeduplicateJoinsPlugin()).selectFrom('bottle as b').selectAll('b')
if (where?.countryCode)
        baseQuery = baseQuery.leftJoin('country as co', 'b.countryId', 'co.id').where('co.alphaCode3', 'in', where.countryCode)
```

```ts
let dataQuery = baseQuery.limit(limit).offset(limit * (page - 1))
case 'country':
                dataQuery = dataQuery.leftJoin('country as co', 'b.countryId', 'co.id').orderBy('co.alphaCode3', orderBy.direction)
```

It's worth noting that every time I have a build error it's because I have a "conditional" `leftJoin` to avoid having a global join if it's not necessary

Hope it help

**Comment by koskimas** [comment] 2023-07-08 11:20
Thanks! I don't know if that should work. You're reassigning to a variable of a different type. The new typescript might just be more strict than the old one.

Have you tried using `$if` for adding the conditional joins?

**Comment by koskimas** [comment] 2023-07-08 11:33
It seems that you can't have a `leftJoin` even inside `$if` with 5.1.6. There's definitely something to fix here.

**Comment by koskimas** [comment] 2023-07-08 12:06
Oh crap. At least the case with `$if` is just a case of typescript being more strict. One of the issues is the return type of the `selectAll()` method not being assignable when you have a `leftJoin`.

A simple example: Let's say we have two tables

```ts
type Person = {
  id: string
  name: string
}

type Pet = {
  id: string
  species: string
}
```

Let's say we have this simple query:

```ts
db.selectFrom('person')
  .innerJoin('pet', 'pet.id', 'person.id')
  // We don't need to even call `selectAll`. The output type is
  // compared when you reassign the query builder.
  .select('pet.species')
```

The output type of `selectAll()` method before the join is:

```ts
SelectQueryBuilder<
  { pet: Pet person: Person }, 
  'person', 
  { species: string } & { id: string, name: string, species: string }
>
```

and after the join:

```ts
SelectQueryBuilder<
  { pet: Pet person: Person }, 
  'person' | 'pet', 
  { species: string } & { id: string, name: string, species: string }
>
```

Everything fine here. The latter is assignable to the former.

BUT in case of `leftJoin`, the output type of `selectAll()` is:

```ts
SelectQueryBuilder<
  { pet: Pet person: Person }, 
  'person' | 'pet', 
  { species: string } & { id: string | null, name: string, species: string | null }
>
```

Since in case of left join, the pet columns might be null.

The error is that

```ts
{ id: string | null, name: string, species: string | null }
```

is not assignable to

```ts
{ id: string, name: string, species: string }
```

because `id: string | null` is not assignable `id: string`.

Everything is strictly speaking correct here.

We can work around this in `$if` but the @AzSiAz's code won't work unfortunately, unless we come up with some magic.

**Comment by AzSiAz** [comment] 2023-07-08 13:13
> Thanks! I don't know if that should work. You're reassigning to a variable of different type. The new typescript might just be more strict than the old one.
> 
> Have you tried using `$if` for adding the conditional joins?

> It seems that you can't have a `leftJoin` even inside `$if` with 5.1.6. `innerJoin` works just fine. There's definitely something to fix here.

No, my issue with `$if` is it's not a type assertion so I have to type assert again, use a `!`  or `value ?? ''` knowing and remembering that `''` will never be reached... and it's unfortunately not taking Eslint or Typescript (or the two at the same time) error or warning having to be disable with a comment every time...


> At least the case with `$if` is just a case of typescript being more strict. One of the issues is the return type of the `selectAll()` method not being assignable when you have a `leftJoin`.
> 
> A simple example: Let's say we have two tables
> 
> ```ts
> type Person = {
>   id: string
>   name: string
> }
> 
> type Pet = {
>   id: string
>   species: string
> }
> ```
> 
> Let's say we have this simple query:
> 
> ```ts
> db.selectFrom('person')
>   .innerJoin('pet', 'pet.id', 'person.id')
>   .select('pet.species')
> ```
> 
> **NOTE**: We don't even need to call `selectAll`. The output type is compared when you reassign the query builder.
> 
> The output type of `selectAll()` method before the join is:
> 
> ```ts
> SelectQueryBuilder<
>   { pet: Pet, person: Person }, 
>   'person', 
>   { species: string } & { id: string, name: string, species: string }
> >
> ```
> 
> and after the join:
> 
> ```ts
> SelectQueryBuilder<
>   { pet: Pet, person: Person }, 
>   'person' | 'pet', 
>   { species: string } & { id: string, name: string, species: string }
> >
> ```
> 
> Everything fine here. The latter is assignable to the former.
> 
> BUT in case of `leftJoin`, the output type of `selectAll()` is:
> 
> ```ts
> SelectQueryBuilder<
>   { pet: Pet, person: Person }, 
>   'person' | 'pet', 
>   { species: string } & { id: string | null, name: string, species: string | null }
> >
> ```
> 
> Since in case of left join, the pet columns might be null.
> 
> The error is that
> 
> ```ts
> { id: string | null, name: string, species: string | null }
> ```
> 
> is not assignable to
> 
> ```ts
> { id: string, name: string, species: string }
> ```
> 
> because `id: string | null` is not assignable `id: string`.
> 
> Everything is strictly speaking correct here.

Is a reproduction still needed ?

> We can work around this in `$if` but the @AzSiAz's code won't work unfortunately, unless we come up with some magic.

I mean if `$if` is working I could live with it, I would still need extra step to avoid `!` but it's better than not updating typescript, so I take whatever work best for Kysely maintainability 😁

**Comment by koskimas** [comment] 2023-07-08 14:48
No need for reproduction anymore. The downcasting assignment will never work with `leftJoin`.

You can of course ignore the types in some of these cases. The reduction in type-safety is nonexistent if you do this:

```ts
let baseQuery = kysely
  .withPlugin(new DeduplicateJoinsPlugin())
  .selectFrom('bottle as b')
  .selectAll('b')
  
if (where?.countryCode) {
  baseQuery = baseQuery
    .leftJoin('country as co', 'b.countryId', 'co.id')
    .where('co.alphaCode3', 'in', where.countryCode) as any
}
```

The queries are still type-safe. That sneaky `as any` only tells typescript that "this assignment is ok". I can't think of a case where this would reduce type-safety, as long as you chain stuff to the same variable you assign to.

This just looks ugly and feels like a hack without a comment explaining it.

**Comment by AzSiAz** [comment] 2023-07-08 16:47
This look like the best alternative I can see for now.
`as never` seem to work too, without `any` warning

Thanks 👍

**Comment by koskimas** [comment] 2023-07-08 20:52
I fixed the bug in `$if`. After the next patch release, you can use that if you prefer.

**Comment by koskimas** [comment] 2023-07-09 15:52
0.26.1 is out

**Closed** 2023-09-11 19:47 UTC
Labels: bug, help wanted, typescript, needs more info
