### ISSUE TITLE
Type argument cannot be inferred from usage

### ISSUE THREAD

**Issue by OfficialPesonen** [kysely-org/kysely#403] opened 2023-03-31 08:03 UTC
Hi

I'm trying to create a simple select query that looks like this (I'm using kysely in a Next.js project):

```
export const database = new Kysely<DB>({
    dialect: new PostgresDialect({
        pool: new Pool({
            host: process.env.DATABASE_HOST,
            port: process.env.DATABASE_PORT ? parseInt(process.env.DATABASE_PORT) : 5432,
            database: process.env.DATABASE_NAME,
            user: process.env.DATABASE_USER,
            password: process.env.DATABASE_PASSWORD,
        }),
    }),
});


const run = async () => {
    await database.selectFrom("table").selectAll().execute();
}

run();
```
The query works perfectly fine but for some reason the database.selectFrom("table") throws the following typescript error:
`Type argument cannot be inferred from usage` 

Typescript version: 5.0.2
```
{
    "compilerOptions": {
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "paths": {
            "@/*": ["./src/*"]
        }
    },
    "ts-node": {
        "compilerOptions": {
            "module": "commonjs"
        }
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules"]
}
```

**Comment by koskimas** [comment] 2023-03-31 08:16
You need to call `select` or `selectAll`. Calling `selectFrom` without any selections is not supported.

**Comment by OfficialPesonen** [comment] 2023-03-31 08:31
I changed `strict: false` into `strict: true` (It was left there for some reason :D). I also changed the `target: "ES5"` into `target: "ES2021"` but it made no difference.

**Comment by OfficialPesonen** [comment] 2023-03-31 08:32
> You need to have `strict: true` in `compilerOptions`. Also targetting `ES5` makes no sense. You need to use ES2015 or newer.

I changed `strict: false` into `strict: true` (It was left there for some reason :D). I also changed the `target: "ES5"` into `target: "ES2021"` but it made no difference.

**Comment by koskimas** [comment] 2023-03-31 09:47
Ok.

**Comment by igalklebanov** [comment] 2023-04-02 18:20
> > You need to have `strict: true` in `compilerOptions`. Also targetting `ES5` makes no sense. You need to use ES2015 or newer.
> 
> I changed `strict: false` into `strict: true` (It was left there for some reason :D). I also changed the `target: "ES5"` into `target: "ES2021"` but it made no difference. 

Can you provide a repository that reproduces this issue?

**Comment by igalklebanov** [comment] 2023-07-07 17:47
Closing due to staleness.

**Closed by igalklebanov** 2023-07-07 17:47 UTC
Labels: invalid, typescript, needs more info
