### ISSUE TITLE
Adding the column 'timestamp with time zone' gives an error with the new version 0.27.3

### ISSUE THREAD

**Issue by dsmits32** [kysely-org/kysely#919] opened 2024-03-23 05:40 UTC
The following code will generate an error (invalid column data type "timestamp with time zone") when using the latest version, 0.27.3.

```
const { Kysely, sql, PostgresAdapter, DummyDriver, PostgresIntrospector, PostgresQueryCompiler } = require('kysely');
const db = new Kysely({
    dialect: {
        createAdapter: () => new PostgresAdapter(),
        createDriver: () => new DummyDriver(),
        createIntrospector: (db) => new PostgresIntrospector(db),
        createQueryCompiler: () => new PostgresQueryCompiler(),
    }})
const query = db.schema.alterTable('users').addColumn('registerDate', 'timestamp with time zone');
console.log(query.compile().sql);
```

When using the previous version (0.27.2), this code will work.

**Comment by igalklebanov** [comment] 2024-03-23 07:51
Hey 👋 

If the data type is not in the list, you should use `sql` template tag.

![image](https://github.com/kysely-org/kysely/assets/14938291/508f15bf-ad9d-477e-806e-f3ece9684880)

![image](https://github.com/kysely-org/kysely/assets/14938291/173e6dd6-db68-4861-a7c7-e87535bff8b0)

**Comment by igalklebanov** [comment] 2024-03-23 07:51
duplicate of #908.

**Closed by igalklebanov** 2024-03-23 07:51 UTC

**Comment by dsmits32** [comment] 2024-03-24 02:11
Thank you very much for your prompt and clear reply. It is greatly appreciated.
