### ISSUE TITLE
`eb(ref, op, val)` does not accept `sql` template tag escaped `op` argument.

### ISSUE THREAD

**Issue by igalklebanov** [kysely-org/kysely#1012] opened 2024-05-29 08:23 UTC
Hey 👋 

Seems like `eb(ref, op, val)` does not accept `sql` template tag escaped operators in 2nd argument.

![image](https://github.com/kysely-org/kysely/assets/14938291/a7364256-9c17-42c9-9100-b17c32a20514)
![image](https://github.com/kysely-org/kysely/assets/14938291/e0840d36-047e-423d-86bb-350067b24483)
https://tsplay.dev/NrYbaw

Also, these are uncaught in the kysely playground. (cc @wirekang)

**Comment by koskimas** [comment] 2024-05-29 11:08
Isn't this a duplicate of https://github.com/kysely-org/kysely/issues/891? `eb` assumes the operator is arithmetic and returns the operand type and not bool.

**Comment by igalklebanov** [comment] 2024-05-29 11:21
Oops. Forgot about it. 🫢

**Closed** 2024-05-29 11:22 UTC
Labels: bug, duplicate, api, typescript

**Comment by wirekang** [comment] 2024-06-09 10:51
> Also, these are uncaught in the kysely playground. 

I updated the playground to use newer version of typescript(5.0.2 ->5.4.5), it seems [fixed.](https://kyse.link/#cN4IgpgJglgLg9gJwM4gFyhgTwA5jSKAOxjAQDMBDAYzAAIBJABQBUKAjAGzCVuAB1CtWlAipahAK4BbNqQDcAoVREIxSGAiIBzBYQC+AgWAAe2RDGHFSlGrQAiFGOwpI6-QcOxPO3MU1Y+SLoGhCAANCAAjhKkmPhQUmYIFsC0AMqRHABCcHAcYbRImbR6tGQIcFK0fCAA1piuHJg1ugJUcITqnrQAvNUgAIwAnABMAHQDAGwAHGMADBMthoQQbGONYFQwAGIVUgAUNVBe7FxINQCUirTrYFxbhwQQl9djAO4AFqRgj8oQCDUCkUOAADAB8YJ6IKBmQAPOpNIQtGCQQASYDHPSoVBEMAwEFXDzvL4IH77MBsC69MG0Cm-FSAwqZcGQ6FMjjwjTaFHozHY3H4i6EoTE777cmU6nXIR0mp-AHhdmwjLZXIcFEQqEwjkI7lojHYLE4wh4glha7Cm6fMUSqk9GmykDyxk1HqM4GcxHI-V842moWvEybCQkfYXXQgPQRaAUe4wfBmdRaUkoCL1RpxdAgLC4fBOLThECEChSPCoEALEYAdjGAGZI3ogA)
