### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by cleytoncarvalho** [kysely-org/kysely#453] opened 2023-04-27 22:30 UTC
I receive this error while running a countAll with the NeonDialect.

Code:

`const test = await db.selectFrom('users').select(db.fn.countAll().as('total')).executeTakeFirstOrThrow()`

Error:

`TypeError: Cannot read properties of undefined (reading 'kind')
    at PostgresQueryCompiler.visitNode (/private/projects/apps/frontend/functions/[[path]].js:31219:73)
    at PostgresQueryCompiler.visitAggregateFunction (/private/projects/apps/frontend/functions/[[path]].js:31484:99)
    at PostgresQueryCompiler.visitNode (/private/projects/apps/frontend/functions/[[path]].js:31219:73)
    at PostgresQueryCompiler.visitAlias (/private/projects/apps/frontend/functions/[[path]].js:31286:14)
    at PostgresQueryCompiler.visitNode (/private/projects/apps/frontend/functions/[[path]].js:31219:73)
    at PostgresQueryCompiler.visitSelection (/private/projects/apps/frontend/functions/[[path]].js:31252:14)
    at PostgresQueryCompiler.visitNode (/private/projects/apps/frontend/functions/[[path]].js:31219:73)
    at PostgresQueryCompiler.compileList (/private/projects/apps/frontend/functions/[[path]].js:31263:16)
    at PostgresQueryCompiler.visitSelectQuery (/private/projects/apps/frontend/functions/[[path]].js:31246:449)
    at PostgresQueryCompiler.visitNode (/private/projects/apps/frontend/functions/[[path]].js:31219:73)`

**Comment by igalklebanov** [comment] 2023-04-27 22:35
Hey 👋 

Can you provide a repository that reproduces this?

**Comment by cleytoncarvalho** [comment] 2023-04-28 00:35
Hey!

Here it is: https://github.com/cleytoncarvalho/kysely-temp

Thank you for your reply.

**Comment by koskimas** [comment] 2023-04-28 04:55
This is most likely caused by the dialect using a mich older/newer version of Kysely than you have in your package.json. The query AST is built using one version and then it's passed to a query compiler of another version. You need to make sure the kysely versions have the same minor number.

**Comment by igalklebanov** [comment] 2023-04-28 12:15
> This is most likely caused by the dialect using a much older/newer version of Kysely than you have in your package.json. The query AST is built using one version and then it's passed to a query compiler of another version. You need to make sure the kysely versions have the same minor number.

Confirmed. kysely-neon is bundled with kysely 0.23.x code.

**Comment by cleytoncarvalho** [comment] 2023-04-29 01:37
Amazing. For this fix to be available on npm what are the next steps? Just to understand the process.

**Comment by igalklebanov** [comment] 2023-04-29 19:21
@cleytoncarvalho 

> Amazing. For this fix to be available on npm what are the next steps? Just to understand the process.

Once things are merged, its up to package maintainers to decide what to include in a release and when to publish.

You can, in the meantime, use `pnpm patch` (or https://www.npmjs.com/package/patch-package) to alter the files based on what kysely-neon's master branch builds to.

**Comment by igalklebanov** [comment] 2023-07-07 17:45
A new version of kysely-neon was published to npm 15 days ago. I'm closing this as it's probably resolved.
Feel free to comment here if it's not.

**Closed by igalklebanov** 2023-07-07 17:45 UTC
Labels: custom dialect, postgres, waiting for release
